# Generated by Django 4.1.4 on 2022-12-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default=0, max_length=500, verbose_name='Descripton'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
